# Generated by Django 4.2.3 on 2023-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=100)),
                ('close', models.FloatField(default=True)),
                ('high', models.FloatField(default=True)),
                ('low', models.FloatField(default=True)),
                ('open', models.FloatField(default=True)),
                ('volume', models.IntegerField(default=True)),
                ('instrument', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
